
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 14;
  public static final int NUM_INT = 22;
  public static final int MENOR = 9;
  public static final int ELSE = 3;
  public static final int NUM_FLOAT = 23;
  public static final int FP = 19;
  public static final int IGUAL = 6;
  public static final int MAIOR_IGUAL = 10;
  public static final int WHILE = 4;
  public static final int LOWER_THAN_ELSE = 25;
  public static final int MENOR_IGUAL = 11;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int ID = 24;
  public static final int FC = 21;
  public static final int PV = 17;
  public static final int AP = 18;
  public static final int MAIS = 13;
  public static final int EOF = 0;
  public static final int MULT = 15;
  public static final int DIFERENTE = 7;
  public static final int DIV = 16;
  public static final int AC = 20;
  public static final int error = 1;
  public static final int MAIOR = 8;
  public static final int ATRIBUI = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "IGUAL",
  "DIFERENTE",
  "MAIOR",
  "MENOR",
  "MAIOR_IGUAL",
  "MENOR_IGUAL",
  "ATRIBUI",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "PV",
  "AP",
  "FP",
  "AC",
  "FC",
  "NUM_INT",
  "NUM_FLOAT",
  "ID",
  "LOWER_THAN_ELSE"
  };
}

